/**
 * Converts a GTMReport object to a markdown string and triggers a browser download.
 */

function slug(text) {
  return (text || 'report')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function formatDate(isoString) {
  try {
    return new Date(isoString).toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric',
    })
  } catch {
    return isoString || 'Unknown date'
  }
}

function angleLabel(angle) {
  return { pain_first: 'Pain-First', roi_first: 'ROI-First', curiosity_first: 'Curiosity-First' }[angle] ?? angle
}

function severityEmoji(severity) {
  return { high: '🔴', medium: '🟡', low: '🟢' }[severity] ?? '⚪'
}

function buildMarkdown(report, productName) {
  const lines = []

  lines.push(`# GTM Simulation Report — ${productName || 'Your Product'}`)
  lines.push(`> **Simulation date:** ${formatDate(report.created_at)}  `)
  lines.push('> **Note:** This report is based on synthetic buyer simulation data, not real buyer responses. Validate with real outbound before making major GTM decisions.')
  lines.push('')

  // Executive Summary
  lines.push('## Executive Summary')
  lines.push('')
  lines.push(report.executive_summary || '')
  lines.push('')

  // Best ICP
  const icp = report.best_icp || {}
  lines.push('## Best ICP Segment')
  lines.push('')
  lines.push(`**Segment:** ${icp.segment || 'N/A'}`)
  lines.push('')
  if (icp.confidence_score !== undefined) {
    const pct = Math.round((icp.confidence_score || 0) * 100)
    lines.push(`**Simulation confidence:** ${pct}%`)
    lines.push('')
  }
  if (icp.reasoning) {
    lines.push(icp.reasoning)
    lines.push('')
  }

  // Winning Message
  const wm = report.winning_message || {}
  lines.push(`## Winning Message Angle — ${angleLabel(wm.angle)}`)
  lines.push('')
  lines.push(`**Average interest score:** ${wm.average_score ?? 'N/A'} / 10`)
  lines.push('')
  lines.push(`**Subject line:** ${wm.recommended_subject_line || 'N/A'}`)
  lines.push('')
  lines.push('**Message body:**')
  lines.push('')
  lines.push('```')
  lines.push(wm.recommended_body || '')
  lines.push('```')
  lines.push('')
  if (wm.reasoning) {
    lines.push(`**Why it wins:** ${wm.reasoning}`)
    lines.push('')
  }

  // Top Objections
  const objs = report.top_objections || []
  if (objs.length) {
    lines.push('## Top Objections')
    lines.push('')
    lines.push('| # | Objection | Frequency | Suggested Response |')
    lines.push('|---|-----------|-----------|-------------------|')
    objs.forEach((o, i) => {
      const resp = (o.suggested_response || '').replace(/\|/g, '\\|').replace(/\n/g, ' ')
      lines.push(`| ${i + 1} | ${o.objection || ''} | ×${o.frequency || 1} | ${resp} |`)
    })
    lines.push('')
  }

  // Buyer Readiness
  const br = report.buyer_readiness || {}
  lines.push('## Buyer Readiness')
  lines.push('')
  lines.push(`**Score:** ${br.score ?? 'N/A'} / 10  `)
  lines.push(`**Level:** ${(br.label || 'N/A').toUpperCase()}`)
  lines.push('')
  if (br.reasoning) {
    lines.push(br.reasoning)
    lines.push('')
  }

  // Risk Signals
  const risks = report.risk_signals || []
  if (risks.length) {
    lines.push('## Risk Signals')
    lines.push('')
    risks.forEach(r => {
      lines.push(`### ${severityEmoji(r.severity)} ${r.signal} (${(r.severity || '').toUpperCase()})`)
      lines.push('')
      lines.push(`**Mitigation:** ${r.mitigation || 'N/A'}`)
      lines.push('')
    })
  }

  // Recommended Workflow
  const wf = report.recommended_workflow || {}
  lines.push(`## ${wf.title || 'Recommended Agentic GTM Workflow'}`)
  lines.push('')
  ;(wf.steps || []).forEach((step, i) => {
    lines.push(`${i + 1}. ${step}`)
  })
  lines.push('')

  // 7-Day Experiment
  const days = report.seven_day_experiment || []
  if (days.length) {
    lines.push('## 7-Day Outbound Experiment')
    lines.push('')
    days.forEach(d => {
      lines.push(`### Day ${d.day} — ${d.goal}`)
      lines.push('')
      lines.push(`**Action:** ${d.action || ''}`)
      lines.push('')
      lines.push(`**Success metric:** ${d.success_metric || ''}`)
      lines.push('')
    })
  }

  // Next Experiment
  if (report.next_experiment) {
    lines.push('## Next Experiment to Run')
    lines.push('')
    lines.push(report.next_experiment)
    lines.push('')
  }

  lines.push('---')
  lines.push('*Generated by GTM Simulation Lab. Data is synthetic — simulate before you send.*')

  return lines.join('\n')
}

/**
 * Convert a GTMReport object to markdown and trigger a browser file download.
 * @param {object} report
 * @param {string} productName
 */
export function downloadGTMReport(report, productName) {
  const md = buildMarkdown(report, productName)
  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `gtm-simulation-report-${slug(productName)}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
